name: maven-publish

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github  # Ensure this matches the id in your settings.xml
        settings-path: ${{ github.workspace }}/.m2  # Ensure correct path

    - name: Configure Maven settings
      run: |
        mkdir -p $GITHUB_WORKSPACE/.m2
        echo '<settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.TOKEN }}</password>
            </server>
          </servers>
        </settings>' > $GITHUB_WORKSPACE/.m2/settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Ensure this secret is set
