name: Maven Build and Docker Publish

on:
  push:
    branches:
      - main  # Adjust this to your target branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Optional: Generally useful, not required for Docker Hub

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: List target directory
      run: ls -la target/  # Debugging step to ensure target directory and files exist

    - name: Build Docker image
      run: |
        docker buildx build \
          --tag lithesh/myrepo:latest \
          --tag lithesh/myrepo:${{ github.sha }} \
          .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image
      run: |
        docker push lithesh/your-repository:latest
        docker push lithesh/your-repository:${{ github.sha }}
